### PR TITLE
Updated lodash

### PR DESCRIPTION
**Pull request by georgiashay**
Fixed high severity security alert

### CODE REVIEW

**Comment by npfoss** [comment]
seems like this has broken something so I fixed it on the axios-security PR instead (#269)
image

**Comment by npfoss** [comment]
actually I'm dumb and the other one has the same problem. so let's figure that out on this PR

**Comment by georgiashay** [comment]
That looks like the regex error that's always been there

**Comment by georgiashay** [comment]
Although on second thought 'fa' seems like a valid regex?

**Comment by georgiashay** [comment]
This might not be related to lodash but we should create another issue about invalid regexes only searching by plain text

**Comment by npfoss** [comment]
idk it wasn't happening on master when I sat down 30 mins ago... and it's not on prod either. can't investigate now though gtg sorry. I'll be back tonight

**Comment by georgiashay** [comment]
What steps can I take to recreate the issue?

**Comment by npfoss** [comment]
right now for me if I `npm install` (this branch or master) and then click on anything in search results I get those errors

I'm working on it now though, just give me a bit

**Comment by npfoss** [comment]
update: it's a problem with lookbehinds, not this. merging

**Pull request merged**
