### PR TITLE
remove all lint errors

### PR DESCRIPTION
**Pull request by npfoss**
Things I wasn't sure about that need taking care of:
- [x] `Array prototype is read only, properties should not be added  no-extend-native` in `ConflictDialog.vue`: should we disable this or is that actually bad practice?
- [x] `Unexpected side effect in "autocomplete" computed property  vue/no-side-effects-in-computed-properties` in `ClassSearch.vue`: this does seem like bad practice.

Also almost every single warning is about defining prop types, so that would probably be straightforward to tackle in a subsequent PR if someone wants to take it on. I didn't do it here because the errors took long enough.

### CODE REVIEW

**Comment by georgiashay** [comment]
Extending array prototype probably is bad practice and we only need those functions for certain arrays anyway.  Our use case doesn't fit in the [reasons why you would disable the rule](https://eslint.org/docs/rules/no-extend-native).

For the autocomplete side effect, I think I remember having trouble with a related problem earlier.  I tried tying them together like this:
`'chosenFilters.nameInput': function() {
      return this.searchInput;
    }`
in a computed function but it did not ever call it.  Not sure how to fix the issue

**Comment by npfoss** [comment]
I spent so long debugging that but eventually figured out it wasn't being reactive because the v-if around the search card disappears/appears when the input goes between empty and nonempty, and when a component comes into existence or disappears, the reactive things attached to its props don't get triggered. Changing the v-if to a v-show make the component exist all the time, but be hidden when the condition is false, thus solving the reactivity thing. Jeez.

**Comment by npfoss** [comment]
Please take a close look at those last two commits @georgiashay and make sure my changes shouldn't change any behavior. These ones were more substantial than simple style adjustments.

**Comment by georgiashay** [comment]
I'm seeing that now the search bar juts out a little on page load.  It fixes itself when resized.  Not seeing this behavior on master and I don't think I saw it before the rebase but I can't be sure since I wasn't looking for it.  
image

**Comment by npfoss** [comment]
Oops, good catch, thanks. The problem was that with v-show the component was being created and mounted on pageload (instead of every time it opens), before the inspector's window size modification was taken into account, I guess. Should be fixed now.

**Pull request merged**
