### PR TITLE
remove v-html

### PR DESCRIPTION
**Pull request by npfoss**
...bringing us down to 0 errors and warnings from the linter for the first time since we added it last winter! :tada:

### CODE REVIEW

**Comment by georgiashay** [comment]
It was originally in a v-html to prevent this:

image

Is there any way to preserve the <b> tags without using v-html?  Parse it beforehand or something?

**Comment by ttpcodes** [comment]
Are all of the warnings in the form of a bolded warning and a slightly more detailed sentence following it like this? If this is the case, we'd likely want to have our warning item consist both of a title string and a details string and pass them into separate <b> and <p> tags to display it.

**Comment by georgiashay** [comment]
I checked the FireRoad code and it appears that this is this case

**Comment by npfoss** [comment]
Oh oops I'm just dumb sorry. Was in a hurry and thought this was the class info card one.

This isn't actually a potential vulnerability since this text only comes from FireRoad, which is definitely trusted. So I'll just have the linter ignore it instead, that's much more convenient for flexibility of displaying warnings.

**Comment by georgiashay** [comment]
Wait actually we don't even get these from FireRoad

**Comment by georgiashay** [comment]
It would be pretty easy to get rid of the v-html since we are apparently making them ourselves in the warnings function of Semester.vue

**Comment by npfoss** [comment]
Yeah but like what if we change our minds about how we want warnings to look? With `v-html` the code would only have to change in one place. It's a really convenient way to make the child component agnostic to the format of the warnings coming from above, and doesn't actually pose a security threat, which is all the warning is upset about

**Comment by georgiashay** [comment]
We are injecting some text into the warnings, from the subject ID and last offered semester.  Not sure if this could cause xss problems for custom classes

**Comment by georgiashay** [comment]
Oh actually we are only doing that for subjects that exist in Fireroad's catalog, so it should be fine

**Comment by npfoss** [comment]
Good catch, and good catch. I'll add a warning to our future selves

**Comment by georgiashay** [comment]
Looks good to merge

**Pull request merged**
