### PR TITLE
Add semantic semester names

### LINKED ISSUE #152: semantic semester names
"Freshman Fall (2019)" etc

(leftover from #42)

### PR DESCRIPTION
**Pull request by georgiashay**
Closes #152 

Not 100% sure about if this makes the names too long/if this is necessary?

### CODE REVIEW

**Comment by venkatesh-sivaraman** [comment]
FWIW we discussed this for FireRoad and decided to use “1st Year Fall”, “1st Year Spring” etc. More consistent with how admins don’t like calling first-years “freshmen” for some reason, and also more encompassing of people who take gap years and the like. We can revisit that decision if you guys feel differently

**Comment by georgiashay** [comment]
That would also make them shorter & more consistent length, seems like a good idea

**Comment by georgiashay** [comment]
I tried it that way and I'm not sure it looks great to have 1st/2nd/3rd/etc since we already have the year

**Comment by georgiashay** [comment]
We could remove the year altogether and unify with FireRoad but I think there was a reason we have the year.  Can't remember what the reason is though

**Comment by npfoss** [comment]
(put my thoughts in #152 since they were more a discussion of whether the issue is even a problem)

**Pull request merged**
